#!/usr/bin/env node


'use strict';

const program = require('commander');
const directoryManager = require('./directory-manager');
const childProcess = require('child_process');
const fs = require('fs');
const path = require('path');

const out = fs.openSync(path.join(__dirname, 'out.log'), 'a');
const err = fs.openSync(path.join(__dirname, 'out.log'), 'a');

program
  .version('0.0.1')
  .option('-w --watch', 'Starts all watchers')
  .option('-a --add [file]', 'Add a new watcher. Specify the location of a directory containing a .dirsinkrc file')
  .parse(process.argv);

if(program.watch) {
  const child = childProcess.spawn('node', [path.join(__dirname, 'daemon')], {
    detached: true,
    stdio: [ 'ignore', out, err ]
  });
  child.unref();
  // process.exit(0);
}

if(program.add) {
  directoryManager.add(program.add);
}